### ISSUE TITLE
Migrate From TrueNAS to TalosNAS

### ISSUE THREAD

**Issue by mircea-pavel-anton** [mirceanton/home-ops#339]
I want to onboard my NAS system into my kubernetes cluster as well. The plan here would be to run Talos on it with the ZFS extension to manage my storage.

## To do

- [ ] Configure talhelper to install Talos on my NAS system with the ZFS extension 
- [ ] Create a zfs-toolkit container image, or something similar. This should be a (privileged?) container with zfs installed and the disks mounted so I can manage my pools
- [ ] Create an SMB server docker image
- [ ] Create an iSCSI server docker image
- [ ] Cronjobs for zfs snapshots 
- [ ] Cronjobs for zfs backups 
- [ ] Export disk smart data
- [ ] Export ZFS stats
- [ ] Export system metrics 
- [ ] Grafana Dashboard

**Comment by mirceanton** [comment]
```Dockerfile
FROM alpine:3.12.0

RUN apk add --no-cache --update \
    samba-common-tools \
    samba-client \
    samba-server

COPY smb.conf /etc/samba/smb.conf

EXPOSE 139/tcp 445/tcp

CMD ["smbd", "--foreground", "--log-stdout", "--no-process-group"]
```
