### ISSUE TITLE
Investigate DevPod as a solution for remote development inside the cluster

### ISSUE THREAD

**Issue by mircea-pavel-anton** [mirceanton/home-ops#62]
I want a codespaces-like solution to remotely work on application in my k8s cluster.

Resources:
  - https://devpod.sh/

**Comment by mirceanton** [comment]
Okteto might be a better solution as it spins up dev ENVIRONMENTS and not just PODS -> i.e. databases etc...

**Comment by mircea-pavel-anton** [comment]
Will stick to devcontainers for now
